# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcmd.proto\"\x1a\n\x07\x43ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\",\n\x08Response\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05\x32\x35\n\x0e\x43ommandHandler\x12#\n\nRunCommand\x12\x08.Command\x1a\t.Response\"\x00\x62\x06proto3')



_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_COMMANDHANDLER = DESCRIPTOR.services_by_name['CommandHandler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=13
  _COMMAND._serialized_end=39
  _RESPONSE._serialized_start=41
  _RESPONSE._serialized_end=85
  _COMMANDHANDLER._serialized_start=87
  _COMMANDHANDLER._serialized_end=140
# @@protoc_insertion_point(module_scope)
