# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cmd_pb2 as cmd__pb2


class CommandHandlerStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCommand = channel.unary_unary(
                '/CommandHandler/RunCommand',
                request_serializer=cmd__pb2.Command.SerializeToString,
                response_deserializer=cmd__pb2.Response.FromString,
                )


class CommandHandlerServicer(object):
    """Interface exported by the server.
    """

    def RunCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=cmd__pb2.Command.FromString,
                    response_serializer=cmd__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommandHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommandHandler(object):
    """Interface exported by the server.
    """

    @staticmethod
    def RunCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommandHandler/RunCommand',
            cmd__pb2.Command.SerializeToString,
            cmd__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
