class MockAppSettingsApi():
    def application_settings(self):
        return {
            "default_projects_limit" : 100000,
            "signup_enabled" : True,
            "id" : 1,
            "default_branch_protection" : 2,
            "default_preferred_language" : "en",
            "restricted_visibility_levels" : [],
            "password_authentication_enabled_for_web" : True,
            "after_sign_out_path" : None,
            "max_attachment_size" : 10,
            "max_export_size": 50,
            "max_import_size": 50,
            "max_import_remote_file_size": 10240,
            "max_decompressed_archive_size": 25600,
            "user_oauth_applications" : True,
            "updated_at" : "2016-01-04T15:44:55.176Z",
            "session_expire_delay" : 10080,
            "home_page_url" : None,
            "default_snippet_visibility" : "private",
            "outbound_local_requests_whitelist": [],
            "domain_allowlist" : [],
            "domain_denylist_enabled" : False,
            "domain_denylist" : [],
            "created_at" : "2016-01-04T15:44:55.176Z",
            "default_ci_config_path" : None,
            "default_project_visibility" : "private",
            "default_group_visibility" : "private",
            "gravatar_enabled" : True,
            "container_expiration_policies_enable_historic_entries": True,
            "container_registry_cleanup_tags_service_max_list_size": 200,
            "container_registry_delete_tags_service_timeout": 250,
            "container_registry_expiration_policies_caching": True,
            "container_registry_expiration_policies_worker_capacity": 4,
            "container_registry_token_expire_delay": 5,
            "decompress_archive_file_timeout": 210,
            "repository_storages_weighted": {"default": 100},
            "plantuml_enabled": False,
            "plantuml_url": None,
            "diagramsnet_enabled": True,
            "diagramsnet_url": "https://embed.diagrams.net",
            "kroki_enabled": False,
            "kroki_url": None,
            "terminal_max_session_time": 0,
            "polling_interval_multiplier": 1.0,
            "rsa_key_restriction": 0,
            "dsa_key_restriction": 0,
            "ecdsa_key_restriction": 0,
            "ed25519_key_restriction": 0,
            "ecdsa_sk_key_restriction": 0,
            "ed25519_sk_key_restriction": 0,
            "first_day_of_week": 0,
            "enforce_terms": True,
            "terms": "Hello world!",
            "performance_bar_allowed_group_id": 42,
            "user_show_add_ssh_key_message": True,
            "allow_account_deletion": True,
            "updating_name_disabled_for_users": False,
            "local_markdown_version": 0,
            "allow_local_requests_from_hooks_and_services": True,
            "allow_local_requests_from_web_hooks_and_services": True,
            "allow_local_requests_from_system_hooks": False,
            "asset_proxy_enabled": True,
            "asset_proxy_url": "https://assets.example.com",
            "asset_proxy_whitelist": ["example.com", "*.example.com", "your-instance.com"],
            "asset_proxy_allowlist": ["example.com", "*.example.com", "your-instance.com"],
            "maven_package_requests_forwarding": True,
            "npm_package_requests_forwarding": True,
            "pypi_package_requests_forwarding": True,
            "snippet_size_limit": 52428800,
            "issues_create_limit": 300,
            "raw_blob_request_limit": 300,
            "wiki_page_max_content_bytes": 52428800,
            "require_admin_approval_after_user_signup": False,
            "personal_access_token_prefix": "glpat-",
            "rate_limiting_response_text": None,
            "keep_latest_artifact": True,
            "admin_mode": False,
            "floc_enabled": False,
            "external_pipeline_validation_service_timeout": None,
            "external_pipeline_validation_service_token": None,
            "external_pipeline_validation_service_url": None,
            "jira_connect_application_key": None,
            "jira_connect_proxy_url": None,
            "silent_mode_enabled": False,
            "package_registry_allow_anyone_to_pull_option": True,
            "bulk_import_max_download_file_size": 5120,
            "bulk_import_enabled": True
        }