---
version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 30      
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
