#!/bin/bash

if [ ! -f config.json ]; then
    ./config.sh
fi

arg="$1"

cmd_args=${@:2}

case $arg in
    list)
    ./list_projects.sh;;
    config)
    ./config.sh;;
    stage)
    ./stage_projects.sh $cmd_args;;
    migrate)
    ./migrate_projects.sh;;
    retrieve-groups)
    ./group_cleanup.sh status;;
    retrieve-users)
    ./user_cleanup.sh status;;
esac