[tool.poetry]
name = "congregate"
version = "4.3.0"
description = "GitLab Professional Service Migration Utility"
authors = ["Michael Leopard <mleopard@gitlab.com>", "Petar Prokic <pprokic@gitlab.com>", "Glen Miller <gmiller@gitlab.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pylint = "<=2.0.0"
awscli = "^1.17.17"
boto3 = "^1.11.17"
requests = "^2.22.0"
flask = "^1.1.1"
responses = "^0.10.9"
futures = "^3.3.0"
danger-noodle = "0.1.7"
docopt = "^0.6.2"
gunicorn = "<=20.0.4"
gevent = "^1.4.0"
mock = "<=4.0.1"
autopep8 = "^1.5"
lazy-object-proxy = "1.4.1"
docker = "^4.2.0"
pytest = "<=5.3.5"
pytest-cov = "^2.8.1"
sphinx = "<=2.4.1"
bs4 = "^0.0.1"
lxml = "^4.5.0"
pylint-exit = "^1.1.0"
jsondiff = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
