version: '2'

services:
  gitlab-src:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab-src
    hostname: gitlab-src-local.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |-
        gitlab_rails['initial_root_password'] = '5iveL!fe'
        alertmanager['enable'] = false
    command: 
      [
      "sh",
      "-c",
      "sleep 300 && 
      rm /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/seed/group_seed.rake && 
      cd /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/seed && 
      wget -O group_seed.rake https://gitlab.com/snippets/1936616/raw && 
      gitlab-rake 'gitlab:seed:group_seed[2,root]' & :; 
      /assets/wrapper",
      ]
    ports:
      - '8080:80'
      - '8443:443'
      - '9090:9090'
      - '8022:22'
    networks:
      ldap:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
      - '9022:22'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      ldap:
  congregate:
      image: registry.gitlab.com/gitlab-org/professional-services-automation/tools/migration/congregate:rolling-centos
      container_name: congregate
      hostname: congregate
      privileged: true
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      ports:
          - 8000:8000
      entrypoint: "/bin/bash -c 'sleep infinity'"
      networks:
          ldap:

volumes:
  openldap_data:
    driver: local

networks:
  ldap:
    ipam: 
      driver: default
      config:
        - subnet: 173.28.0.0/29