# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maven.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmaven.proto\":\n\x07\x43ommand\x12\r\n\x05phase\x18\x01 \x01(\t\x12\x12\n\npluginGoal\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\",\n\x08Response\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05\x32:\n\x13MavenCommandHandler\x12#\n\nRunCommand\x12\x08.Command\x1a\t.Response\"\x00\x62\x06proto3')



_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'maven_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'maven_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_MAVENCOMMANDHANDLER = DESCRIPTOR.services_by_name['MavenCommandHandler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=15
  _COMMAND._serialized_end=73
  _RESPONSE._serialized_start=75
  _RESPONSE._serialized_end=119
  _MAVENCOMMANDHANDLER._serialized_start=121
  _MAVENCOMMANDHANDLER._serialized_end=179
# @@protoc_insertion_point(module_scope)
