version: '3'

services:
    bitbucket:
        image: bitbucket-seed:latest
        restart: always
        ports:
            - "7990:7990"
            - "7999:7999"
        depends_on:
            - postgres
        hostname: 'bitbucket'
        environment:
            - SETUP_LICENSE=$BITBUCKET_LICENSE
            - SETUP_BASEURL=https://bitbucket.yourcompany.com
            - SETUP_SYSADMIN_USERNAME=admin
            - SETUP_SYSADMIN_PASSWORD=$BITBUCKET_PASSWORD
            - SETUP_SYSADMIN_DISPLAYNAME=John Doe
            - SETUP_SYSADMIN_EMAILADDRESS=sysadmin@yourcompany.com
            - ELASTICSEARCH_ENABLED=false
            - JDBC_DRIVER=org.postgresql.Driver
            - JDBC_USER=db_user
            - JDBC_PASSWORD=db_password
            - JDBC_URL=jdbc:postgresql://postgres:5432/bitbucket
        volumes:
            - $CONGREGATE_PATH/test-data/bitbucket:/var/atlassian/application-data/bitbucket
        networks:
            default:
                aliases: 
                    - bitbucket


    postgres:
        image: postgres:11.8-alpine
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - database.env
        volumes:
            - $CONGREGATE_PATH/test-data/database:/var/lib/postgresql/data/
        hostname: 'postgres'
        networks:
            default:
                aliases: 
                    - postgres

