class MockGroupsApi():

    def get_single_group(self):
        return {
            "id": "ac4f77cb-966f-49ae-b942-13471223719e",
            "name": "MyShuttle",
            "description": "Generated by Azure DevOps Demo Generator",
            "url": "https://dev.azure.com/gitlab-ps/_apis/projects/ac4f77cb-966f-49ae-b942-13471223719e",
            "state": "wellFormed",
            "revision": 77,
            "visibility": "private",
            "lastUpdateTime": "2024-08-16T07:53:59.77Z"
        }