class MockProjectsApi():

    def get_single_project(self):
        return {
            "id": "fab6c524-9c20-4564-8f38-3a90f188d651",
            "name": "eShopOnWeb",
            "description": "Generated by Azure DevOps Demo Generator",
            "url": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651",
            "state": "wellFormed",
            "revision": 21,
            "_links": {
                "self": {
                    "href": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651"
                },
                "collection": {
                    "href": "https://dev.azure.com/gitlab-ps/_apis/projectCollections/62d5db69-917f-405d-973d-fc20e7ecd3de"
                },
                "web": {
                    "href": "https://dev.azure.com/gitlab-ps/eShopOnWeb"
                }
            },
            "visibility": "private",
            "defaultTeam": {
                "id": "3b66f663-9820-4840-9ed9-3904ab5eb5c8",
                "name": "eShopOnWeb Team",
                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651/teams/3b66f663-9820-4840-9ed9-3904ab5eb5c8"
            },
            "lastUpdateTime": "2024-04-11T19:37:34.61Z"
        }

    def get_all_repositories(self):
        return [{
            "id": "06b48f27-94eb-4229-abd8-ca6be39b4c48",
            "name": "eShopOnWeb",
            "url": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48",
            "project": {
                "id": "fab6c524-9c20-4564-8f38-3a90f188d651",
                "name": "eShopOnWeb",
                "description": "Generated by Azure DevOps Demo Generator",
                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651",
                "state": "wellFormed",
                "revision": 21,
                "visibility": "private",
                "lastUpdateTime": "2024-04-11T19:37:34.61Z"
            },
            "defaultBranch": "refs/heads/main",
            "size": 62568090,
            "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
            "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/eShopOnWeb/eShopOnWeb",
            "webUrl": "https://dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
            "isDisabled": False,
            "isInMaintenance": False
        }]
