
class MockRepositoriesApi():

    def get_single_repository(self):
        return {
            "id": "06b48f27-94eb-4229-abd8-ca6be39b4c48",
            "name": "eShopOnWeb",
            "url": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48",
            "project": {
                "id": "fab6c524-9c20-4564-8f38-3a90f188d651",
                "name": "eShopOnWeb",
                "description": "Generated by Azure DevOps Demo Generator",
                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651",
                "state": "wellFormed",
                "revision": 21,
                "visibility": "private",
                "lastUpdateTime": "2024-04-11T19:37:34.61Z"
            },
            "defaultBranch": "refs/heads/main",
            "size": 62568090,
            "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
            "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/eShopOnWeb/eShopOnWeb",
            "webUrl": "https://dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
            "_links": {
                "self": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48"
                },
                "project": {
                    "href": "vstfs:///Classification/TeamProject/fab6c524-9c20-4564-8f38-3a90f188d651"
                },
                "web": {
                    "href": "https://dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb"
                },
                "ssh": {
                    "href": "git@ssh.dev.azure.com:v3/gitlab-ps/eShopOnWeb/eShopOnWeb"
                },
                "commits": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48/commits"
                },
                "refs": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48/refs"
                },
                "pullRequests": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48/pullRequests"
                },
                "items": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48/items"
                },
                "pushes": {
                    "href": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48/pushes"
                }
            },
            "isDisabled": False,
            "isInMaintenance": False
        }

    def get_all_repositories(self):
        return {
            "value": [
                {
                    "id": "06b48f27-94eb-4229-abd8-ca6be39b4c48",
                    "name": "eShopOnWeb",
                    "url": "https://dev.azure.com/gitlab-ps/fab6c524-9c20-4564-8f38-3a90f188d651/_apis/git/repositories/06b48f27-94eb-4229-abd8-ca6be39b4c48",
                    "project": {
                        "id": "fab6c524-9c20-4564-8f38-3a90f188d651",
                        "name": "eShopOnWeb",
                        "description": "Generated by Azure DevOps Demo Generator",
                        "url": "https://dev.azure.com/gitlab-ps/_apis/projects/fab6c524-9c20-4564-8f38-3a90f188d651",
                        "state": "wellFormed",
                        "revision": 21,
                        "visibility": "private",
                        "lastUpdateTime": "2024-04-11T19:37:34.61Z"
                    },
                    "defaultBranch": "refs/heads/main",
                    "size": 62568090,
                    "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
                    "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/eShopOnWeb/eShopOnWeb",
                    "webUrl": "https://dev.azure.com/gitlab-ps/eShopOnWeb/_git/eShopOnWeb",
                    "isDisabled": False,
                    "isInMaintenance": False
                }
            ],
            "count": 1
        }