
class MockRepositoriesApi():

    def get_single_repository(self):
        return {
            "id": "b2071745-4b0b-4cde-a177-9422f7cbd811",
            "name": "Azure Bicep Workshop",
            "url": "https://dev.azure.com/gitlab-ps/20671faf-e1bd-4226-8172-0cdf0fdb7128/_apis/git/repositories/b2071745-4b0b-4cde-a177-9422f7cbd811",
            "project": {
                "id": "20671faf-e1bd-4226-8172-0cdf0fdb7128",
                "name": "Azure Bicep Workshop",
                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/20671faf-e1bd-4226-8172-0cdf0fdb7128",
                "state": "wellFormed",
                "revision": 29,
                "visibility": "private",
                "lastUpdateTime": "2024-04-11T21:11:29.787Z"
            },
            "defaultBranch": "refs/heads/main",
            "size": 8037569,
            "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/Azure%20Bicep%20Workshop/_git/Azure%20Bicep%20Workshop",
            "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/Azure%20Bicep%20Workshop/Azure%20Bicep%20Workshop",
            "webUrl": "https://dev.azure.com/gitlab-ps/Azure%20Bicep%20Workshop/_git/Azure%20Bicep%20Workshop",
            "isDisabled": False,
            "isInMaintenance": False
        }

    def get_all_repositories(self):
        return {
                "value": [
                        {
                            "id": "9c766a24-385b-4931-afe4-245ad2e915aa",
                            "name": "infra",
                            "url": "https://dev.azure.com/gitlab-ps/ac4f77cb-966f-49ae-b942-13471223719e/_apis/git/repositories/9c766a24-385b-4931-afe4-245ad2e915aa",
                            "project": {
                                "id": "ac4f77cb-966f-49ae-b942-13471223719e",
                                "name": "MyShuttle",
                                "description": "Generated by Azure DevOps Demo Generator",
                                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/ac4f77cb-966f-49ae-b942-13471223719e",
                                "state": "wellFormed",
                                "revision": 77,
                                "visibility": "private",
                                "lastUpdateTime": "2024-08-16T07:53:59.77Z"
                            },
                            "defaultBranch": "refs/heads/main",
                            "size": 0,
                            "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/MyShuttle/_git/infra",
                            "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/MyShuttle/infra",
                            "webUrl": "https://dev.azure.com/gitlab-ps/MyShuttle/_git/infra",
                            "isDisabled": False,
                            "isInMaintenance": False
                        },
                        {
                            "id": "8630e352-f5b2-4abc-a25c-00a931f0cda2",
                            "name": "MyShuttle",
                            "url": "https://dev.azure.com/gitlab-ps/ac4f77cb-966f-49ae-b942-13471223719e/_apis/git/repositories/8630e352-f5b2-4abc-a25c-00a931f0cda2",
                            "project": {
                                "id": "ac4f77cb-966f-49ae-b942-13471223719e",
                                "name": "MyShuttle",
                                "description": "Generated by Azure DevOps Demo Generator",
                                "url": "https://dev.azure.com/gitlab-ps/_apis/projects/ac4f77cb-966f-49ae-b942-13471223719e",
                                "state": "wellFormed",
                                "revision": 77,
                                "visibility": "private",
                                "lastUpdateTime": "2024-08-16T07:53:59.77Z"
                            },
                            "defaultBranch": "refs/heads/master",
                            "size": 1700362,
                            "remoteUrl": "https://gitlab-ps@dev.azure.com/gitlab-ps/MyShuttle/_git/MyShuttle",
                            "sshUrl": "git@ssh.dev.azure.com:v3/gitlab-ps/MyShuttle/MyShuttle",
                            "webUrl": "https://dev.azure.com/gitlab-ps/MyShuttle/_git/MyShuttle",
                            "isDisabled": False,
                            "isInMaintenance": False
                        }
                    ],
                    "count": 2
                }